[package]
name = "syouyu-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aes-gcm = "0.10.3"
chrono.workspace = true
getrandom = "0.3.4"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
syouyu-domain.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
