[package]
name = "syouyu-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
http.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
serde_json.workspace = true
syouyu-domain.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
