{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syouyu.serviceAccountName" . }}
  labels:
    {{- include "syouyu.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.garage.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syouyu.garageServiceAccountName" . }}
  labels:
    {{- include "syouyu.labels" . | nindent 4 }}
    app.kubernetes.io/component: garage
  {{- with .Values.garage.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
